baseURL = "/"
languageCode = "en-us"
title = "xAIM"
summaryLength = "20"

[params]
# hero
hero_title ="eXplainable Artificial Intelligence in Healthcare Management"
hero_sub_title ="A Connecting Europe Facility in Telecom project INEA/CEF/ICT/A2020/2276680"

# about 
about_title ="About the Project"

# team
team_title = "Project Team"

# news
news_title = "Latest News"

# partners
partners_title = "Partners"
partners_sub_title = ""

# contact
contact_title ="Contact Us"
location = "Via San Felice 5, 27100 Pavia, Italy"
email = "mariachiara.demartini@unipv.it"
phone_number = "+39.0382.986201"

# newsletter
newsletter_title = "Our Newsletter"
newsletter_sub_title = "Tamen quem nulla quae legam multos aute sint culpa legam noster magna"